// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.28.3
// source: transport/vless/client_addons.proto

package vless

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientAddons struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flow    string `protobuf:"bytes,1,opt,name=Flow,proto3" json:"Flow,omitempty"`
	Seed    []byte `protobuf:"bytes,2,opt,name=Seed,proto3" json:"Seed,omitempty"`
	TraceId string `protobuf:"bytes,3,opt,name=TraceId,proto3" json:"TraceId,omitempty"`
	Token   string `protobuf:"bytes,6,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *ClientAddons) Reset() {
	*x = ClientAddons{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_vless_client_addons_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientAddons) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAddons) ProtoMessage() {}

func (x *ClientAddons) ProtoReflect() protoreflect.Message {
	mi := &file_transport_vless_client_addons_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAddons.ProtoReflect.Descriptor instead.
func (*ClientAddons) Descriptor() ([]byte, []int) {
	return file_transport_vless_client_addons_proto_rawDescGZIP(), []int{0}
}

func (x *ClientAddons) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

func (x *ClientAddons) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

func (x *ClientAddons) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ClientAddons) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_transport_vless_client_addons_proto protoreflect.FileDescriptor

var file_transport_vless_client_addons_proto_rawDesc = []byte{
	0x0a, 0x23, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x76, 0x6c, 0x65, 0x73,
	0x73, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74,
	0x2e, 0x76, 0x6c, 0x65, 0x73, 0x73, 0x22, 0x66, 0x0a, 0x0c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x41, 0x64, 0x64, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x6c, 0x6f, 0x77, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x46, 0x6c, 0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x65,
	0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x53, 0x65, 0x65, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x54, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x54, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x2e,
	0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x61, 0x67,
	0x65, 0x72, 0x6e, 0x65, 0x74, 0x2f, 0x73, 0x69, 0x6e, 0x67, 0x2d, 0x62, 0x6f, 0x78, 0x2f, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x76, 0x6c, 0x65, 0x73, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transport_vless_client_addons_proto_rawDescOnce sync.Once
	file_transport_vless_client_addons_proto_rawDescData = file_transport_vless_client_addons_proto_rawDesc
)

func file_transport_vless_client_addons_proto_rawDescGZIP() []byte {
	file_transport_vless_client_addons_proto_rawDescOnce.Do(func() {
		file_transport_vless_client_addons_proto_rawDescData = protoimpl.X.CompressGZIP(file_transport_vless_client_addons_proto_rawDescData)
	})
	return file_transport_vless_client_addons_proto_rawDescData
}

var file_transport_vless_client_addons_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_transport_vless_client_addons_proto_goTypes = []interface{}{
	(*ClientAddons)(nil), // 0: transport.vless.ClientAddons
}
var file_transport_vless_client_addons_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transport_vless_client_addons_proto_init() }
func file_transport_vless_client_addons_proto_init() {
	if File_transport_vless_client_addons_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_transport_vless_client_addons_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientAddons); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transport_vless_client_addons_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transport_vless_client_addons_proto_goTypes,
		DependencyIndexes: file_transport_vless_client_addons_proto_depIdxs,
		MessageInfos:      file_transport_vless_client_addons_proto_msgTypes,
	}.Build()
	File_transport_vless_client_addons_proto = out.File
	file_transport_vless_client_addons_proto_rawDesc = nil
	file_transport_vless_client_addons_proto_goTypes = nil
	file_transport_vless_client_addons_proto_depIdxs = nil
}
